blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://www.tensr.xyz/documentation
    about: Check our documentation for answers to common questions

  - name: ğŸ’¬ Community Forum
    url: https://www.tensr.xyz
    about: Please ask and answer questions here

  - name: ğŸ¤ Support
    url: https://www.tensr.xyz
    about: Get help with installation and usage
